# /* ----------- ðŸ’« https://github.com/JaKooLit ðŸ’« -------- */ #

[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
